

import ChatWrapper from '@/context'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>React Chat App</title>
      </head>

      <body>
        <ChatWrapper>
          <main className="">{children}</main>
        </ChatWrapper>
      </body>
    </html>
  )
}
