import ChatWrapper from '@/context'
import './globals.css'
import ToasterContext from '@/context/ToasterContext'
import AuthContext from '@/context/AuthContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>React Chat App</title>
      </head>

      <body>
        <ChatWrapper>
          <AuthContext>
            <ToasterContext />
            <main className="">{children}</main>
          </AuthContext>
        </ChatWrapper>
      </body>
    </html>
  )
}
